# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f55d6aeeebb265973d00d4c2fec10a153d266d50d0275e3643b9f243f34b1e06b76645b2026808ba307d4bcb7b2d8dbfe2bccefb397bbe636e1cea8f98d8bc1b

test:
  secret_key_base: 173e19ebbb53361dd1baa91c502e4bf498507668d7db57e05cff044e81d6cf93f22e31ecb930c7efe74820dca24cc0bfe00c9bb22d6ddf02b99761a50deffef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
